CREATE TABLE REFERENCER.T_COMPANY (
    ID VARCHAR(40) PRIMARY KEY NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    DESCRIPTION VARCHAR(250) NOT NULL,
    TEAM_ID VARCHAR(40) NOT NULL
    );

CREATE TABLE REFERENCER.T_TEAM_MEMBERS (
    ID VARCHAR(40) PRIMARY KEY NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    TEAM_ID VARCHAR (40) NOT NULL,
    ROLE VARCHAR (12) NOT NULL
);

CREATE TABLE REFERENCER.T_CONTACT (
    ID VARCHAR(40) PRIMARY KEY NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    ADDRESS VARCHAR(250) NOT NULL,
    PRIMARY_PHONE VARCHAR(50) NOT NULL,
    SECONDARY_PHONE VARCHAR(50)
);